Vagrant.configure("2") do |config|
  config.vm.define "postfix" do |node|
    node.vm.box = "generic/centos7"
    node.vm.hostname = "srv-postfix"
    node.vm.provision "shell", path: "postfix.sh"
  end

end
