# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # make vm node1 - master
  config.vm.define "node1" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "172.16.10.100"
    node.vm.provision "shell", path: "setup-master.sh"   
  end

  # make vm node2 - worker
  config.vm.define "node2" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "node2"
    node.vm.network "private_network", ip: "172.16.10.101"
    node.vm.provision "shell", path: "setup-node.sh"
  end

  # make vm node3 - worker
  config.vm.define "node3" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "node3"
    node.vm.network "private_network", ip: "172.16.10.102"
    node.vm.provision "shell", path: "setup-node.sh"
  end

end
