Vagrant.configure("2") do |config|
  config.vm.define "cron" do |node|
    node.vm.box = "hieunt84/centos7"
    node.vm.hostname = "srv-cron"
    node.vm.provision "shell", path: "cron.sh"
  end

end
