Vagrant.configure("2") do |config|

  # make vm db1
  config.vm.define "nginx" do |node|
    node.vm.box = "hieunt84/centos7"
    node.vm.hostname = "ser-nginx"
    node.vm.network "public_network", ip: "172.20.10.202"
    node.vm.provision "shell", path: "setup-nginx.sh"
  end

end
