Vagrant.configure("2") do |config|

  # make vm
  config.vm.define "wp" do |node|
    node.vm.box = "hieunt84/centos7"
    node.vm.hostname = "ser-wp"
    node.vm.network "private_network", ip: "192.168.56.99"
    node.vm.provision "shell", path: "wp.sh"
  end

end
