Vagrant.configure("2") do |config|

  # make vm db1
  config.vm.define "srv-db1" do |node|
    node.vm.box = "generic/centos7"
    node.vm.hostname = "srv-db1"
    node.vm.network "private_network", ip: "192.168.56.99"
    node.vm.provision "shell", path: "setup-mariadb.sh"
  end

end
