Vagrant.configure("2") do |config|
  config.vm.define "hocvps" do |node|
    node.vm.box = "generic/centos7"
    node.vm.hostname = "srv-hocvps"
    node.vm.network "private_network", ip: "192.168.55.10"
    #node.vm.provision "shell", path: "hocvps.sh"
  end

end
